receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  logging:
    verbosity: detailed
  otlphttp/jaeger:
    endpoint: "http://jaeger:4318"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors:
      exporters: [ logging, otlphttp/jaeger ]
