apiVersion: v1
kind: Service
metadata:
  name: datapool-manager-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
  namespace: dpm
  labels:
    app: datapool-manager
spec:
  type: LoadBalancer
  selector:
    app: datapool-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9192
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datapool-manager-deploy
  namespace: dpm
  labels:
    app: datapool-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datapool-manager
  template:
    metadata:
      labels:
        app: datapool-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: datapool-manager-container
        image: thekiwisre/datapool-manager:latest
        ports:
        - containerPort: 9192
